### ISSUE TITLE
Suggestion : remove the dependancy on TMDB API

### ISSUE THREAD

**Issue by computamike** [Sainsburys/dtp-be-ts#2]
I have a suggestion : Instead of relying on TMDB's REST API - it might be an idea to provide a fake API that can be called instead.   You could bake a set of JSON files into the project, and serve them from [JSON-SERVER](https://www.npmjs.com/package/json-server). This would allow you to test without relying on the API key or TMDB being available. 

You can still supply an API key, and get JSON-SERVER to only return a valid token, and would allow you to test expired tokens etc.

Having a set of JSON files allows you to build a set of tests that you could use to determine what error conditions the candidate identified correctly.

**Comment by smbkr** [comment]
Hi Mike,

Thanks for the suggestion! That definitely makes sense and is something I may consider, the ability to test with specific error scenarios would certainly be interesting. That being said, we time box the task and don't often get to the stage of error handling and edge cases.

At the moment we're trying to keep the task & config as simple as possible, and leave some room for the candidate to write their own tests for the features they're implementing in the test, but I'll definitely keep this in mind for any future revisions.

Appreciate you taking the time to comment
